const state={channel:'axon',kind:'All',query:'',selected:null};
const messages={
  axon:[
    ['Bruno','B','Can we expose artifacts in Discord directly, maybe like a side drawer that opens per channel or conversation?'],
    ['Axon','A','Yes. The lightest standalone prototype is a message-linked artifact index with an overlay drawer: files, generated previews, plans, diffs, and run evidence grouped by channel/thread.','drawer-prototype'],
    ['Bruno','B','I need to see if it’s cumbersome. It should feel native to this dark Discord setup, not like a giant gray app shoved into the side.'],
    ['Axon','A','Prototype stance: keep Discord as the cockpit, add a thin artifact rail, and open a translucent drawer only when needed.']
  ],
  handoffs:[['Bruno','B','Give Thalamus access to the Plane API and make sure GitHub credential lanes are handled cleanly.'],['Axon','A','I’ll keep the handoff evidence separate from the chat transcript and pin the credential-path checklist here.','plane-api-handoff']],
  canaries:[['Bruno','B','Check Broca. Grok does not seem to be doing Balanced, Structured, or Grammar again.'],['Axon','A','Broca Prompt Assist was in raw mode; xAI OAuth proxy is healthy and mode canaries passed.','broca-grok-canary']],
  artifacts:[['Axon','A','This channel can act as a flat artifact index if the drawer is closed or unavailable.','artifact-index']],
  a2a:[['Bruno','B','Return back to A2A and continue the work.'],['Axon','A','The drawer can expose worker outputs without requiring every agent to spam the main channel.','a2a-worker-map']],
  'general-personal':[['Bruno','B','Keep this low-scroll and phone-readable.'],['Axon','A','Understood. The drawer stays optional; summaries remain primary in chat.']]
};
const artifacts=[
  {id:'drawer-prototype',channel:'axon',kind:'Mockup',title:'Discord artifact drawer standalone',owner:'Axon',age:'now',format:'HTML + PNG',desc:'Glassy overlay, slim rail, scoped artifact index, detail state, compact mode, and mobile-width behavior.',scope:'#axon channel + current thread',actions:'Open, copy link, pin, handoff',risk:'Discord plugin/webview constraints still need a real integration spike.',evidence:'Rendered locally with Chrome headless screenshots.'},
  {id:'plane-api-handoff',channel:'handoffs',kind:'Handoff',title:'Plane API access for Thalamus',owner:'Ops',age:'14m',format:'checklist',desc:'Credential path, validation checklist, and worker-lane ownership notes for Thalamus.',scope:'#handoffs',actions:'Open checklist, assign worker, attach evidence',risk:'Secrets must stay in Agent Vault/Infisical references; no raw tokens in chat.',evidence:'Pending handoff receipt card.'},
  {id:'broca-grok-canary',channel:'canaries',kind:'Canary',title:'Broca Prompt Assist Grok health',owner:'Voice',age:'22m',format:'logs',desc:'Balanced, Structured, and Grammar direct proxy canaries passed against xAI OAuth proxy.',scope:'#canaries + local Broca config',actions:'Open diagnostics, copy health summary',risk:'If Broca pastes raw after this, the issue is likely hotkey/mode path, not Grok.',evidence:'8645 health authenticated; direct chat completions returned expected mode outputs.'},
  {id:'bp-logo-sketches',channel:'axon',kind:'Image',title:'Blue Paladin BP mark sketches',owner:'Brand',age:'yesterday',format:'10 files',desc:'Negative-space monogram directions filtered for readability and no helmet/mascot cues.',scope:'#axon / brand review',actions:'Open board, mark favorites',risk:'Over-clever negative space may read as only P/B or abstract glyph.',evidence:'Prior generated board plus memory canon.'},
  {id:'artifact-index',channel:'artifacts',kind:'Index',title:'Flat artifact index fallback',owner:'Axon',age:'today',format:'list',desc:'A fallback when the overlay is closed: artifact cards can still be posted as normal Discord summaries.',scope:'#artifacts',actions:'Open, filter, copy canonical links',risk:'Flat channel gets noisy if every run emits full evidence.',evidence:'This standalone UI models the filtered drawer alternative.'},
  {id:'a2a-worker-map',channel:'a2a',kind:'Run',title:'A2A worker output map',owner:'A2A',age:'today',format:'run evidence',desc:'Worker outputs grouped by board/project so chat stays concise while evidence remains reachable.',scope:'#a2a workers',actions:'Open run, inspect evidence, promote summary',risk:'Needs canonical ledger/link IDs to avoid stale transcript sludge.',evidence:'Modeled as run artifact in drawer.'}
];
const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
function renderMessages(){const wrap=$('#messages');wrap.innerHTML='';(messages[state.channel]||messages.axon).forEach((m,i)=>{const [name,avatar,text,artifactId]=m;const node=document.createElement('article');node.className='msg';node.innerHTML=`<div class="avatar">${avatar}</div><div><div class="meta"><span class="name">${name}</span><span class="time">Today ${String(10+i).padStart(2,'0')}:${42+i}</span></div><div class="text">${text}</div>${artifactId?`<button class="chip" data-artifact="${artifactId}"><span>◆</span>${artifactTitle(artifactId)}</button>`:''}</div>`;wrap.appendChild(node)});$$('.chip').forEach(c=>c.onclick=()=>openDetail(c.dataset.artifact));}
function artifactTitle(id){return artifacts.find(a=>a.id===id)?.title||'Artifact';}
function artifactPool(){return artifacts.filter(a=>a.channel===state.channel);}
function renderTabs(){const kinds=['All',...new Set(artifactPool().map(a=>a.kind))];$('#kindTabs').innerHTML=kinds.map(k=>`<button class="tab ${state.kind===k?'active':''}" data-kind="${k}">${k}</button>`).join('');$$('.tab').forEach(t=>t.onclick=()=>{state.kind=t.dataset.kind;renderArtifacts();renderTabs();});}
function renderArtifacts(){const pool=artifactPool().filter(a=>(state.kind==='All'||a.kind===state.kind)&&(`${a.kind} ${a.title} ${a.desc} ${a.owner} ${a.evidence}`.toLowerCase().includes(state.query)));$('#railCount').textContent=pool.length;$('#artifactList').innerHTML=pool.map(a=>`<article class="artifact-card" data-id="${a.id}"><div class="card-top"><span class="kind">${a.kind}</span>${a.age==='now'?'<span class="badge">new</span>':''}</div><h3>${a.title}</h3><p>${a.desc}</p><div class="card-foot"><span>${a.owner} · ${a.age}</span><span>${a.format}</span></div></article>`).join('')||'<p class="empty">No artifacts match this filter.</p>';$$('.artifact-card').forEach(c=>c.onclick=()=>openDetail(c.dataset.id));}
function openDetail(id){const a=artifacts.find(x=>x.id===id);if(!a)return;state.selected=id;$('#drawerListView').hidden=true;const d=$('#drawerDetailView');d.hidden=false;d.innerHTML=`<button class="back" id="backToList">← Back to artifacts</button><div class="kind">${a.kind}</div><h1>${a.title}</h1><p>${a.desc}</p><div class="detail-preview">${a.format} preview / evidence card</div><div class="kv"><b>Scope</b><span>${a.scope}</span><b>Actions</b><span>${a.actions}</span><b>Evidence</b><span>${a.evidence}</span><b>Risk</b><span>${a.risk}</span></div><div class="detail-actions"><button class="button primary" data-toast="Opened ${a.title}">Open</button><button class="ghost-action" data-toast="Copied artifact link">Copy link</button><button class="ghost-action" data-toast="Pinned artifact to #${state.channel}">Pin</button><button class="ghost-action" data-toast="Prepared handoff card">Handoff</button></div>`;$('#backToList').onclick=backToList;$$('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));setDrawerOpen(true);}
function backToList(){state.selected=null;$('#drawerDetailView').hidden=true;$('#drawerListView').hidden=false;}
function setChannel(ch){state.channel=ch;state.kind='All';state.query='';state.selected=null;$$('.channel').forEach(c=>c.classList.toggle('active',c.dataset.channel===ch));$('#channelTitle').textContent=ch;$('#composerChannel').textContent=ch;$('#drawerChannel').textContent='#'+ch;$('#artifactSearch').value='';backToList();renderMessages();renderTabs();renderArtifacts();}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
function hydrate(){let saved={};try{saved=JSON.parse(localStorage.getItem('drawerPrototype')||'{}')||{};}catch{saved={};}if(saved.density)document.body.classList.toggle('compact',saved.density==='compact');if(saved.glass){document.documentElement.style.setProperty('--glass',saved.glass+'%');$('#glassRange').value=saved.glass;}$('#densitySelect').value=document.body.classList.contains('compact')?'compact':'comfortable';}
function persist(){localStorage.setItem('drawerPrototype',JSON.stringify({density:$('#densitySelect').value,glass:$('#glassRange').value}));}
function setDrawerOpen(open){$('#artifactDrawer').classList.toggle('open',open);$('#toggleDrawer').setAttribute('aria-expanded',String(open));$('#drawerRail').setAttribute('aria-expanded',String(open));}
function toggleDrawer(){setDrawerOpen(!$('#artifactDrawer').classList.contains('open'));}
$('#toggleDrawer').onclick=toggleDrawer;$('#drawerRail').onclick=toggleDrawer;$('#pinArtifact').onclick=()=>toast('Pinned current message context as an artifact shell');$('#artifactSearch').oninput=e=>{state.query=e.target.value.toLowerCase();renderArtifacts();};$('#resetFilters').onclick=()=>{state.kind='All';state.query='';$('#artifactSearch').value='';renderTabs();renderArtifacts();};$('#densitySelect').onchange=e=>{document.body.classList.toggle('compact',e.target.value==='compact');persist();};$('#glassRange').oninput=e=>{document.documentElement.style.setProperty('--glass',e.target.value+'%');persist();};$$('.channel').forEach(c=>c.onclick=()=>setChannel(c.dataset.channel));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.selected)backToList();else if(e.key==='Escape')setDrawerOpen(false);else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){setDrawerOpen(true);$('#artifactSearch').focus();e.preventDefault();}});
hydrate();
const params=new URLSearchParams(location.search);
setChannel(params.get('channel')||'axon');
if(params.get('closed')==='1') setDrawerOpen(false); else setDrawerOpen($('#artifactDrawer').classList.contains('open'));
if(params.get('compact')==='1'){document.body.classList.add('compact');$('#densitySelect').value='compact';}
if(params.get('detail')) openDetail(params.get('detail'));
if(params.get('q')){$('#artifactSearch').value=params.get('q');state.query=params.get('q').toLowerCase();renderArtifacts();}
